# Generated by Django 5.0.6 on 2024-06-03 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hudud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tashkilot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hudud')),
            ],
        ),
        migrations.CreateModel(
            name='Bino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('maydon', models.IntegerField()),
                ('qavat', models.IntegerField()),
                ('parkovka', models.BooleanField(default=False)),
                ('plashatka', models.BooleanField(default=False)),
                ('lift', models.BooleanField(default=False)),
                ('hudud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.hudud')),
                ('tashkilot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tashkilot')),
            ],
        ),
    ]
